apiVersion: v1
kind: Secret
type: kubernetes.io/opaque
metadata:
  name: fluentd-cloudwatch
  namespace: kube-system
  labels:
    app: fluentd-cloudwatch
    env: system
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key  | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_key | b64enc }}
