apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-cloudwatch
  namespace: kube-system
  labels:
    app: fluentd-cloudwatch
    env: system
data:
  AWS_REGION: {{ .Values.aws.region }}
  CW_LOG_GROUP: {{ .Values.aws.loggroup }}